model:
  num_input_channels: 2
  num_output_channels: 1
  stft_chunk_size: 96
  stft_pad_size: 64
  stft_back_pad: 96
  num_layers: 3
  latent_dim: 16
  hidden_channels: 64
  speaker_dim: 20
  bidirectional: false
  film_preset: "all_except_first"

data:
  sr: 16000
  duration: 5
  fg_dir: "BinauralCuratedDataset/scaper_fmt"
  noise_dir: "BinauralCuratedDataset/noise_scaper_fmt"
  hrtf_list: "BinauralCuratedDataset/hrtf/CIPIC/train_hrtf.txt"
  hrtf_type: "CIPIC"
  num_fg_range: [1, 1]
  num_bg_range: [0, 0]
  num_noise_range: [1, 1]
  snr_range_fg: [5, 15]
  snr_range_bg: [0, 10]
  batch_size: 8
  num_workers: 8
  samples_per_epoch: 20000

training:
  backend: "lightning"
  max_epochs: 200
  optimizer: "AdamW"
  lr: 0.001
  weight_decay: 0.0
  grad_clip: 1.0
  scheduler: "ReduceLROnPlateau"
  scheduler_params:
    factor: 0.5
    patience: 5

loss:
  l1_ratio: 10

evaluation:
  metrics: ["si_sdri", "snri"]

checkpointing:
  monitor: "val/loss"
  mode: "min"
  save_dir: "runs/tse"
  patience: 20
